---
- name: Manage NetBox Regions
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - netbox.netbox

  vars_files:
    - secrets.yaml
    - config.yaml

  tasks:
    # - name: Manage base entities.
    #   import_tasks: tasks/base.yaml

    - name: Setup facilities.
      import_tasks: tasks/facilities.yaml

    # - name: Manage IPAM.
    #   import_tasks: tasks/ipam.yaml

    # - name: Manage devices.
    #   import_tasks: tasks/devices.yaml
