---
- name: Manage NetBox Regions
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - netbox.netbox

  vars_files:
    - secrets.yaml
    - config.yaml

  tasks:
    - name: Ensure target tags exists.
      netbox_tag:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: "{{ validate_certs }}"
        data:
            name: "{{ item.name }}"
            slug: "{{ item.slug }}"
            color: "{{ item.color }}"
        state: present
      loop: "{{ nb_tags }}"
    
    - name: Ensure target regions exists.
      netbox_region:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        validate_certs: "{{ validate_certs }}"
        data:
          name: "{{ item.name }}"
          slug: "{{ item.slug }}"
          description: "{{ item.description }}"
          tags:
            - "source-ansible"
        state: present
      loop: "{{ regions }}"
