---
- name: Ensure regions exist.
  netbox_region:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ validate_certs }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      parent_region: "{{ item.parent_region | default(omit, true) }}"
      description: "{{ item.description | default(omit, true) }}"
      custom_fields: "{{ item.custom_fields }}"
      tags:
        - "source-ansible"
    state: present
  loop: "{{ regions }}"

- name: Ensure sites exist.
  netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ validate_certs }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      region: "{{ item.region | default(omit, true) }}"
      status: "{{ item.status }}"
      time_zone: "{{ item.time_zone | default(omit, true)  }}"
      physical_address: "{{ item.physical_address | default(omit, true)  }}"
      latitude: "{{ item.latitude | default(omit, true)  }}"
      longitude: "{{ item.longitude | default(omit, true)  }}"
      description: "{{ item.description | default(omit, true) }}"
      custom_fields:
        custom_id: "{{ item.custom_id }}"
      tags:
        - "source-ansible"
    state: present
  loop: "{{ sites }}"

- name: Build generated locations from sites and location blueprint.
  set_fact:
    generated_locations: |
      {%- set generated_locations = [] -%}
      {%- for s in sites -%}
        {%- for l in location_blueprint -%}
          {%- set location = {
              'name': l.name,
              'slug': s.slug ~ '-' ~ l.slug_suffix,
              'site': s.slug,
              'status': l.status,
              'description': l.description | default('', true),
              'custom_fields': l.custom_fields
            } -%}
          {%- if l.parent_suffix | default(None, true) -%}
            {%- set _ = location.update({'parent_location': s.slug ~ '-' ~ l.parent_suffix}) -%}
          {%- endif -%}
          {%- set _ = generated_locations.append(location) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ generated_locations }}

- name: Ensure locations exist.
  netbox_location:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ validate_certs }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      parent_location: "{{ item.parent_location | default(omit, true) }}"
      site: "{{ item.site }}"
      status: "{{ item.status }}"
      description: "{{ item.description | default(omit, true) }}"
      custom_fields: "{{ item.custom_fields }}"
      tags:
        - "source-ansible"
    state: present
  loop: "{{ locations + generated_locations }}"

# Rack type module missing

- name: Build generated racks from sites and rack blueprint.
  set_fact:
    generated_racks: |
      {%- set generated_racks = [] -%}
      {%- for s in sites -%}
        {%- for r in rack_blueprint -%}
          {%- set rack = {
              'name': r.name,
              'site': s.slug,
              'location': s.slug ~ '-' ~ r.location_suffix,
              'status': r.status,
              'width': r.width,
              'u_height': r.u_height,
              'desc_units': r.desc_units,
              'description': r.description | default('', true),
            } -%}
          {%- set _ = generated_racks.append(rack) -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ generated_racks }}

- name: Ensure racks exist.
  netbox_rack:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ validate_certs }}"
    data:
      name: "{{ item.name }}"
      site: "{{ item.site }}"
      location: "{{ item.location }}"
      status: "{{ item.status }}"
      # airflow, missing in ansible module
      # form_factor, missing in ansible module
      width: "{{ item.width }}"
      # starting_unit, missing in ansible module
      u_height: "{{ item.u_height }}"
      desc_units: "{{ item.desc_units }}"
      description: "{{ item.description | default(omit, true) }}"
      tags:
        - "source-ansible"
    state: present
  loop: "{{ racks + generated_racks }}"
