---
- name: Ensure regions exists.
  netbox_region:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ validate_certs }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      parent_region: "{{ item.parent_region | default(omit, true) }}"
      description: "{{ item.description | default(omit, true) }}"
      custom_fields: "{{ item.custom_fields | default(omit, true) }}"
      tags:
        - "source-ansible"
    state: present
  loop: "{{ regions }}"

- name: Ensure sites exists.
  netbox_site:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    validate_certs: "{{ validate_certs }}"
    data:
      name: "{{ item.name }}"
      slug: "{{ item.slug }}"
      description: "{{ item.description | default(omit, true) }}"
      region: "{{ item.region | default(omit, true) }}"
      status: "{{ item.status }}"
      time_zone: "{{ item.time_zone | default(omit, true)  }}"
      physical_address: "{{ item.physical_address | default(omit, true)  }}"
      latitude: "{{ item.latitude | default(omit, true)  }}"
      longitude: "{{ item.longitude | default(omit, true)  }}"
      tags:
        - "source-ansible"
    state: present
  loop: "{{ sites }}"